### Signup
POST http://localhost:8000/api/v1/auth/signup
Content-Type: application/json

{
    "name": "Harsh",
    "email": "harsh@example.com",
    "password": "password123",
    "phone": "9876543210"
}

### Login
POST http://localhost:8000/api/v1/auth/login
Content-Type: application/json

{
    "email": "harsh@example.com",
    "password": "password123"
}

### Wrong password
POST http://localhost:8000/api/v1/auth/login
Content-Type: application/json

{
    "email": "harsh@example.com",
    "password": "wrongpassword"
}